# Generated by Django 4.1.4 on 2022-12-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('check_type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=64)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='bill_service.point')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('kitchen', 'kitchen'), ('client', 'client')], max_length=64)),
                ('order', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], max_length=64)),
                ('pdf_file', models.FileField(upload_to='media/pdf')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='bill_service.point')),
            ],
        ),
    ]
