# Generated by Django 4.1.4 on 2022-12-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='media/pdf'),
        ),
    ]
